name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: npm
      - run: npm ci --include=dev
      - run: npm run build
        env:
          CI: true
          NODE_ENV: production
